<a href="https://colab.research.google.com/github/analyticswithadam/Python/blob/main/YouTube_Comments_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
dev = "AIzaSyAs4K5uKayP7nJEdty2lHqbt8GN_I3qMk8"

## Pull All Comments

In [35]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = "AIzaSyAs4K5uKayP7nJEdty2lHqbt8GN_I3qMk8"

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)

request = youtube.commentThreads().list(
    part="snippet",
    videoId="fn3KWM1kuAw",
    maxResults=100
)

comments = []

# Execute the request.
response = request.execute()

# Get the comments from the response.
for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

while (1 == 1):
  try:
   nextPageToken = response['nextPageToken']
  except KeyError:
   break
  nextPageToken = response['nextPageToken']
  # Create a new request object with the next page token.
  nextRequest = youtube.commentThreads().list(part="snippet", videoId="-GJgqIJsTME", maxResults=100, pageToken=nextPageToken)
  # Execute the next request.
  response = nextRequest.execute()
  # Get the comments from the next response.
  for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

df = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','public'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 727 entries, 0 to 726
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      727 non-null    object
 1   updated_at  727 non-null    object
 2   like_count  727 non-null    int64
 3   text        727 non-null    object
 4   public      727 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 23.6+ KB

In [3]:
response['items'][0]

{'kind': 'youtube#commentThread',
 'etag': '2hmdEl6muD3m9jShSPaQZvOhFSg',
 'id': 'UgwFDBYvbcwcgDTQEuZ4AaABAg',
 'snippet': {'channelId': 'UC2utQmYluWGlhV-W0rTA2wg',
  'videoId': '-GJgqIJsTME',
  'topLevelComment': {'kind': 'youtube#comment',
   'etag': 'MIHU7HC3wPmFBBNl6rjuYh6B7Os',
   'id': 'UgwFDBYvbcwcgDTQEuZ4AaABAg',
   'snippet': {'channelId': 'UC2utQmYluWGlhV-W0rTA2wg',
    'videoId': '-GJgqIJsTME',
    'textDisplay': 'I’m so glad you’re back in Paris. Finishing what you fucking started',
    'textOriginal': 'I’m so glad you’re back in Paris. Finishing what you fucking started',
    'authorDisplayName': '@soccball991',
    'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/APkrFKZmnwXxo47AWQj-xUEnTiTf83-r5ErZkbdGmBei=s48-c-k-c0x00ffffff-no-rj',
    'authorChannelUrl': 'http://www.youtube.com/channel/UCgCkAIHnA2pysH2ADY-faxQ',
    'authorChannelId': {'value': 'UCgCkAIHnA2pysH2ADY-faxQ'},
    'canRate': True,
    'viewerRating': 'none',
    'likeCount': 0,
    'publishedAt': '2023-10-23T15:15:29Z',
    'updatedAt': '2023-10-23T15:15:44Z'}},
  'canReply': True,
  'totalReplyCount': 0,
  'isPublic': True}}

In [4]:
df.head(10)

,author,updated_at,like_count,text,public
0,@RealEagleScout,2023-12-01T12:48:52Z,0,"Bustin a move, like Gregory Hines, or.. Melody...",True
1,@juliemccannon2908,2023-12-01T10:06:51Z,1,I wish I could afford a Spot. I would love to ...,True
2,@c431inf,2023-12-01T01:25:59Z,1,Amazing and disturbing,True
3,@johnluber9957,2023-11-30T20:47:03Z,3,"as far as I can tell, i see three outcomes.\n\...",True
4,@wades_world22,2023-11-30T18:28:57Z,1,just incredible,True
5,@user-eg7hb7od2v,2023-11-30T17:56:54Z,0,"Ну, вот и артистов не надо.",True
6,@harishpadale,2023-11-30T04:42:44Z,1,SCIENCE START DO NOT THINK OFF Countries RELAT...,True
7,@ivabuckley-wn6ig,2023-11-29T22:16:13Z,0,"Amazing, can I have one ☝️ lol",True
8,@CSGdesign01,2023-11-29T10:43:28Z,3,Not long now....,True
9,@lucianene7741,2023-11-28T22:20:33Z,2,Can you make a robot play guitar?,True

## Sort by Likes and Get Top 10

In [5]:
df.sort_values(by='like_count', ascending=False)[0:10]

,author,updated_at,like_count,text,public
711,@dirtsmegee,2023-10-23T15:05:53Z,1012,Action needs an 8 part series in every country...,True
616,@Nolanbrown480,2023-10-23T16:59:11Z,686,Clovis’ energy is absolutely unmatched. The pe...,True
582,@ActionBronsonMusic,2023-10-23T17:53:02Z,552,PARIS. WITH LOVE.,True
716,@uknownutin3528,2023-10-23T15:01:03Z,490,One of the best food series on YouTube. LONG L...,True
725,@BigTunaBoy420,2023-10-23T12:30:09Z,263,One of the best and most authentic eating shows,True
665,@urbanprojectz,2023-10-23T15:59:02Z,160,This is a game changer for food/cooking/review...,True
689,@elmejortrabajodelmundo,2023-10-23T15:26:47Z,71,"""From Paris with Love"" makes me happy for real...",True
724,@cheng8841,2023-10-23T12:57:25Z,66,"""eight part series"" LETS GOOOOOO",True
598,@yorkshireguy6671,2023-10-23T17:15:43Z,64,Action and Clovis in Paris always looks like t...,True
693,@InspectahReese,2023-10-23T15:25:27Z,49,If y’all love Clovis he raps in French! You ha...,True

#Pull all Comments for Multiple Videos

## 1. Get Comments Function

In [6]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = "AIzaSyAs4K5uKayP7nJEdty2lHqbt8GN_I3qMk8"

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)


def getcomments(video):
  request = youtube.commentThreads().list(
      part="snippet",
      videoId=video,
      maxResults=100
  )

  comments = []

  # Execute the request.
  response = request.execute()

  # Get the comments from the response.
  for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  while (1 == 1):
    try:
     nextPageToken = response['nextPageToken']
    except KeyError:
     break
    nextPageToken = response['nextPageToken']
    # Create a new request object with the next page token.
    nextRequest = youtube.commentThreads().list(part="snippet", videoId=video, maxResults=100, pageToken=nextPageToken)
    # Execute the next request.
    response = nextRequest.execute()
    # Get the comments from the next response.
    for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  df2 = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','video_id','public'])
  return df2

In [7]:
df = getcomments("fn3KWM1kuAw")
df

,author,updated_at,like_count,text,video_id,public
0,@RealEagleScout,2023-12-01T12:48:52Z,0,"Bustin a move, like Gregory Hines, or.. Melody...",fn3KWM1kuAw,True
1,@juliemccannon2908,2023-12-01T10:06:51Z,1,I wish I could afford a Spot. I would love to ...,fn3KWM1kuAw,True
2,@c431inf,2023-12-01T01:25:59Z,1,Amazing and disturbing,fn3KWM1kuAw,True
3,@johnluber9957,2023-11-30T20:47:03Z,3,"as far as I can tell, i see three outcomes.\n\...",fn3KWM1kuAw,True
4,@wades_world22,2023-11-30T18:28:57Z,1,just incredible,fn3KWM1kuAw,True
...,...,...,...,...,...,...
98555,@henry55,2020-12-29T18:52:09Z,0,eow,fn3KWM1kuAw,True
98556,@JackSmith-oq7op,2020-12-29T18:52:09Z,0,Oh boy,fn3KWM1kuAw,True
98557,@iliketurtles4869,2020-12-29T18:52:07Z,2,I like turtles,fn3KWM1kuAw,True
98558,@ibrax1,2020-12-29T18:52:05Z,1,test,fn3KWM1kuAw,True
98559,@tinotibaldo,2020-12-29T18:52:03Z,9,First,fn3KWM1kuAw,True

In [28]:
df.to_csv('all_comments.csv', sep=';', index=False)

In [33]:
df.head(500)

                 author                                               text
0       @RealEagleScout  Bustin a move, like Gregory Hines, or.. Melody...
1    @juliemccannon2908  I wish I could afford a Spot. I would love to ...
2              @c431inf                             Amazing and disturbing
3        @johnluber9957  as far as I can tell, i see three outcomes.\n\...
4        @wades_world22                                    just incredible
..                  ...                                                ...
495  @margaretharks7304                                        Cool video!
496  @PattyBryant-mh4dd  This So Greats 🤩😉 They were NSync  also😀 Just ...
497       @billlamb7923            Love it! Now those are some happy bots.
498             @LPM147  I too remember these happy times before our en...
499        @Bhairab_roy                      After killing all the humans:

[500 rows x 2 columns]

In [ ]:
first_500_comments = df.head(500)
print(first_500_comments)

In [ ]:
'''
first_500_comments = first_500_comments.drop("public")
first_500_comments = first_500_comments.drop("video_id")
first_500_comments = first_500_comments.drop("updated_at")
first_500_comments = first_500_comments.drop("like_count")
'''

first_500_comments.head(100)
abc = "asdf"


#first_500_comments.to_csv('first_500_comments.csv', sep=';', index=False)